[build-system] 
requires = ["hatchling"] 
build-backend = "hatchling.build" 

[project] 
name = "example_packaging" 
dependencies = ["numpy"]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest"]

[tool.hatch]
version.path = "src/example_packaging/__init__.py"
